language: generic
sudo: required
install: true
services:
- docker
git:
  submodules: true
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: test
    script:
    - ./run.tests.sh
  - stage: publish
    script:
    - ./do.package.sh
    - ./do.publish.sh
    env:
    - BRANCH=${TRAVIS_BRANCH}
  - stage: deploy
    script:
    - ./do.deploy.sh
branches:
  only:
  - master
  - develop
env:
  global:
  - secure: vArgzkHm5J+EEwllFVHpDZBwEruCuEHeNRuZezzSMKzzygclALtotqOsvApwer6olUJMWnEH/rEDq0vNhQFyjL+maKxJUCbCq/i7uiG9yPZuHILjBJiOfO5NgoOxuXxkRT/5xPFThEkWhXi7OaOLPwpZ/FxhRZ37WaZQtTYYduNRK4RTkKMtM2UJbRCOKT2eymb/ChW52JqQfBMZrdOT96lyKybXRiXUJEP4Gdt+TDVq4pAjLBuZCryGlJ9h6189coiQstsOML/yMHmzc8A9HLoSROR/lNwYOBDogwn/rLdn1zwfRGLR0it1Xqll/6j425pWF8e4E3DAPZX60p3gqW3qDyqBIadxNELD3f0oB50elsGRL4g6dT2Xh3PA0Ni4KyuNnQ28TQMP8S8Fh7Rd+x9HWQovhhRmkBtYWBbXVG6Sl82FUVgEBlJJb79hLzxZaEgPZav9IkfEJdCzUtBv/I8FkW0qtR7YnPuAWUYxf6Ceoz7iE1rMFWvHZGek9OYg/kUoMry7ASee1f0tLSYca3F+WybH/p5cEwTmUBxO7tLzm80yFcduHqJSs1WIA+WXad68/HPWCth/nIrpubaKM85vvqUCH6pJ63JIcBhSslypwbq9w0IcSH+gBAwqBoTP948b952qYQelegRRTbL6PmyaC8apUMEUkolwwZ7VMQ0=
  - secure: LV5I9FB8YJxE985ibUCO82Tv/vgyNaWBH9jrf97ydjN3MngrBxJn7FIa3XCQ1nYIddJwfCjD4IekHVA0pixs3FzBBtcbq+H13KUKt7Y+mjKyyZSSkp959eH1rO3CM3XfAolOx0wKwCXecRjSeDfOYTFRxjdLWRpy3YeyQdX7T5MHl79bdTCZKumO1NBwzytsyDjj0vMoz3n1JaF26JuBOqAkPJ0ztvR3UrOTtUk7c2PGFcxESa89Q+55PE0QvENZOA0FUFz8w4eBHkRSyh3bRgJTfPTP/Vm5dxVTKDXW4t5YgeJgf2GNJW7W8dU9/dmj80GaL836fwKF6FPBjP8X539t8gck3pKdJtiMms6uBgmVzNxQa7o/a3ZteBut7TDx8ZGmfWkDn10rLXDwq4RfrCq6pAztJF7Q3CiXyosLzfzgUnArsGGUky2lSz/YA/oHHxI10a7G0SFMj/Ajd4ZSl1+C/18IQE/eDzgvkYabHspDR0/ifRW4pZcN266Di+zr+XTFt6TxNQ3tvnHsMmwO8etysyu3Cy+8ObQibsjzI26sKZiXfU4OY204K+y78g+EJuYYLRRj3lTQ0iWr72U6wVYGZm+XFuHOBUrihlWJ0NmMsrUTejcmIWC29G8uc8q35hX4X4KSz6g6IBrS5MCcTWOub/n3KclAxFw6M6QmwIs=
  - secure: t0+Qnjt4mSfdbxGSCZjVUQEoHjNh+PGLRTvnN39CvoTtjSWDd8j7NtiHnFzw5qgYx+U454PpnSZHNz5vYwntDz7kDzQGz+XkLGmypYAD2SRPTPAVkuL3FgRSsvuzs/iFCjo7dJR1tWj3Wuz0xzly2Ju9PctG50jRV+dPi2htmoiURX0RGiSc4Tn042Z5ZNn1VsRw5CWXyp8TTdblBSz0A6Bq/n97SjY6oO8dWR8jHbgBON498u/XZnH5sWsQ4R88bdvMU3HfkdxkGyiejJ8vctWr+QlsA7fT40BhlkxcuHQEFXkZi3mDJoxhkUQ+kd5lX+aR8oY2WqG3F9PmoVWHM7IeFNJrLokbE7PacNfQWqUsZI2detBMg8Jrjm3t3gRxKcVnV2fEr3LbtgiC7bsWRuV2VQiq0ecOMxOCLzx53XbOBkxI6pKoaSIACq4Z7lvszxKM7xDSzHBTY+RBqovE0nzl7rUQQSMpDWhl36ARAmt5FrMxF4Gb45t32Wai+sm+pkXhhjYwVszpkVY+QXIIuZFQPtAdpHhg1QWPZlH+NsaZoKil9SgihasKkNEn7bErzSdp61PJP6ovGOCMinI+Abfn6tF9NYB3T4pd8LALWS+ttywfbM3eAKYNUgaXSgCyr7Fz4IB7Gs9OHdAocQ8Z94yfzngEZ6cWRYH6oL2Cdrw=
