build:
  debug: true
  compress: false
  secure: false
  devtool: 'source-map'
  cssSourceMaps: true
  cssLocalName: '[name]_[local]_[hash:base64:3]'
  verbose: true
  useHMR: true
  output:
    filename: '[name].js?[hash]'
    chunkFilename: '[id].js?[chunkhash]'
  stats:
    colors: true
    reasons: true
    hash: false
    version: false
    timings: false
    chunks: false
    chunkModules: false
    cached: false
    cachedAssets: false

environment:
  process.env.serverApiUrl: 'http://localhost:2701/api'



