build:
  debug: false
  compress: true
  secure: true
  devtool: false,
  cssSourceMaps: false
  cssLocalName: '[hash:base64:4]'
  verbose: false
  useHMR: false
  output:
    filename: '[name].[hash].js'
    chunkFilename: '[id].[chunkhash].js'
  stats:
    colors: true
    reasons: false
    hash: true
    version: true
    timings: true
    chunks: true
    chunkModules: true
    cached: false
    cachedAssets: false

environment:
  process.env.serverApiUrl: 'http://localhost:2701/api'
