build:
  debug: false
  compress: true
  secure: true
  devtool: 'source-map'
  cssSourceMaps: true
  cssLocalName: '[hash:base64:4]'
  verbose: false
  useHMR: false
  output:
    filename: '[name].[hash].js'
    chunkFilename: '[id].[chunkhash].js'
  stats:
    colors: true
    reasons: true
    hash: false
    version: false
    timings: false
    chunks: false
    chunkModules: false
    cached: false
    cachedAssets: false

environment:
  process.env.serverApiUrl: 'https://just-married-sta-server.herokuapp.com/api'
